config/routes.rb
Hashtag::Application.routes.draw do
  root to: 'searches#new'
  resources :searches, only: [:create, :show]
end

app/models/fake_twitter.rb
require 'ostruct'

class FakeTwitter
  def self.clear
    @tweets = Hash.new([])
  end

  def self.[]=(term, tweet_data)
    @tweets ||= {}
    @tweets[term] = tweet_data
  end

  def self.search(term)
    @tweets ||= {}
    tweets = @tweets[term].map do |tweet_datum|
      Twitter::Status.new(tweet_datum.merge(id: 1234))
    end

    OpenStruct.new(results: tweets)
  end
end

app/models/search.rb
class Search
  class_attribute :search_api
  self.search_api = Twitter

  def initialize(search_term)
    @search_term = search_term
  end

  def each(&block)
    search_api.search(@search_term).results.each(&block)
  end
end

app/models/searcher.rb
class Searcher
  class_attribute :backend
  self.backend = Twitter

  def initialize(term)
    @term = term
  end

  def each(&block)
    backend.search(@term).results.each &block
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new

  end

  def create
    term = params[:search][:search_term].gsub(/^#(.*)/, '\1')
    redirect_to search_path(term)
  end

  def show
    @search_term = "##{params[:id]}"
    @results = Searcher.new(@search_term)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
  end

  def show
    search_term = "##{params[:id]}"
    @tweets = Searcher.new(search_term).search
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hashtag</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/homepage.html.erb
<%= form_for :searches, url: '/searches' do |form| %>
  <%= form.label :search_term %>
  <%= form.text_field :search_term %>
  <%= form.submit 'Search' %>
<% end %>

app/views/searches/_form.html.erb
<%= form_for :search, url: searches_path do |form| %>
  <%= form.label :search_term %>
  <%= form.text_field :search_term, value: search_term %>
  <%= form.submit 'Submit' %>
<% end %>

app/views/searches/new.html.erb
<%= render 'form', search_term: nil %>

app/views/searches/show.html.erb
<%= render 'form', search_term: @search_term %>

<ul class="results">
  <% @results.each do |result| %>
    <li>
      <%= result.text %>
      <span data-role="author"><%= result.from_user %></span>
    </li>
  <% end %>
</ul>

app/views/tweets/index.html.erb
<form id='search_form'>
  <input type='text' class='search' id='search_term' />
  <input type='submit' value='Search' />
</form>

app/views/tweets/show.html.erb
<ul class='tweets'>
  <% @tweets.each do |tweet| %>
    <li><%= tweet.text %> <%= tweet.from_user_name %></li>
  <% end %>
</ul>